### ISSUE TITLE
not able to install it properly. 

### ISSUE THREAD

**Issue by collegeimprovements** [ember-weekend/ember-weekend#41]
I ran `git clone https://github.com/ember-weekend/ember-weekend/issues/new`
then `cd ember-weekend` and after that ran `npm install` and `bower install`. 

But when I run `ember s` I get the following error.

```ruby
`libsass` bindings not found. Try reinstalling `node-sass`?
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/ashah/Desktop/ember-weekend/node_modules/ember-cli-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/ashah/Desktop/ember-weekend/node_modules/ember-cli-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ashah/Desktop/ember-weekend/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:5:12)
    at Module._compile (module.js:425:26)
```

How can I reinstall `node-sass` ?

**Comment by code0100fun** [comment]
Woah, I totally missed this issue. Sorry.

I've had this issue with `libsass` too. Assuming you are on a Mac I think the fix is to do something like:

* brew unlink libsass
* brew install libsass
* rm -rf node_modules
* npm cache clear
* npm install

This [issue](https://github.com/sass/node-sass/issues/918) on node-sass explains the problem well.

**Comment by collegeimprovements** [comment]
This is helpful. Thanks a lot for your reply.
